#cloud-config

# Installera .NET Runtime 8.0
runcmd:
  # Registrera Microsofts repository (som inkluderar .NET Runtime 8.0-paketet)
  - wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - dpkg -i packages-microsoft-prod.deb

  # Installera .NET Runtime 8.0
  - apt-get update
  - apt-get install -y aspnetcore-runtime-8.0

# Skapa en tjänst för applikationen
write_files:
  - path: /etc/systemd/system/Uppgift_2.service
    content: |
      [Unit]
      Description=ASP.NET Web App running on Ubuntu

      [Service]
      WorkingDirectory=/opt/Uppgift_2
      ExecStart=/usr/bin/dotnet /opt/Uppgift_2/Uppgift_2.dll
      Restart=always
      RestartSec=10
      KillSignal=SIGINT
      SyslogIdentifier=Uppgift_2
      User=www-data
      Environment=ASPNETCORE_ENVIRONMENT=Production
      Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
      Environment="ASPNETCORE_URLS=http://*:5000"

      [Install]
      WantedBy=multi-user.target
    owner: root:root
    permissions: '0644'

systemd:
  units:
    - name: Uppgift_2.service
      enabled: true
